# Generated by Django 6.0.2 on 2026-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_credit_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
